create extension if not exists pgcrypto;

create table if not exists public.diagnosis_participants (
  id uuid primary key default gen_random_uuid(),
  participant_code text not null unique,
  token text not null,
  diagnosis_result text not null check (diagnosis_result in ('coloring', 'meal', 'sweet')),
  pass_type text check (pass_type in ('advance', 'same_day')),
  source text not null default 'direct',
  diagnosed_on date not null,
  event_eligible boolean not null default false,
  preview_used boolean not null default false,
  artwork_status text not null default 'not_submitted'
    check (artwork_status in ('not_submitted', 'submitted', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.participation_events (
  id bigint generated by default as identity primary key,
  participant_code text not null references public.diagnosis_participants(participant_code) on delete cascade,
  event_type text not null check (event_type in (
    'diagnosis_completed',
    'table_qr_opened',
    'preview_started',
    'coloring_started',
    'artwork_submitted'
  )),
  source text not null default 'direct',
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists diagnosis_participants_diagnosed_on_idx
  on public.diagnosis_participants (diagnosed_on desc);

create index if not exists diagnosis_participants_result_idx
  on public.diagnosis_participants (diagnosis_result, pass_type);

create index if not exists participation_events_code_time_idx
  on public.participation_events (participant_code, occurred_at desc);

alter table public.diagnosis_participants enable row level security;
alter table public.participation_events enable row level security;

create or replace view public.sheet_participation_export as
select
  p.participant_code,
  p.diagnosed_on,
  p.diagnosis_result,
  p.pass_type,
  p.source,
  p.event_eligible,
  p.preview_used,
  p.artwork_status,
  p.created_at,
  p.updated_at,
  count(e.id) filter (where e.event_type = 'table_qr_opened') as table_qr_count,
  count(e.id) filter (where e.event_type = 'coloring_started') as coloring_start_count,
  count(e.id) filter (where e.event_type = 'artwork_submitted') as artwork_submit_count
from public.diagnosis_participants p
left join public.participation_events e on e.participant_code = p.participant_code
group by p.id;

revoke all on public.diagnosis_participants from anon, authenticated;
revoke all on public.participation_events from anon, authenticated;
revoke all on public.sheet_participation_export from anon, authenticated;
