create table if not exists public.diagnosis_campaign_users (
  id uuid primary key default gen_random_uuid(),
  campaign_id text not null,
  line_user_id text not null,
  line_display_name text,
  source text not null default 'line',
  first_opened_at timestamptz not null default now(),
  last_opened_at timestamptz not null default now(),
  opened_count integer not null default 1 check (opened_count > 0),
  diagnosis_started_at timestamptz,
  diagnosis_completed_at timestamptz,
  diagnosed_on date,
  diagnosis_result text check (diagnosis_result in ('coloring', 'meal', 'sweet')),
  answers jsonb not null default '[]'::jsonb,
  participant_code text unique references public.diagnosis_participants(participant_code) on delete set null,
  coupon_code text unique,
  coupon_type text check (coupon_type in ('coloring_pass', 'meal_tea_120_off', 'warabi_tea_120_off')),
  coupon_send_status text not null default 'not_sent'
    check (coupon_send_status in ('not_sent', 'sent', 'failed')),
  coupon_sent_at timestamptz,
  coupon_redeemed_at timestamptz,
  coupon_last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (campaign_id, line_user_id)
);

create table if not exists public.diagnosis_campaign_events (
  id bigint generated by default as identity primary key,
  campaign_user_id uuid not null references public.diagnosis_campaign_users(id) on delete cascade,
  event_type text not null check (event_type in (
    'diagnosis_opened',
    'diagnosis_started',
    'diagnosis_completed',
    'duplicate_access',
    'coupon_sent',
    'coupon_send_failed',
    'coupon_redeemed',
    'coupon_redeem_duplicate'
  )),
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists diagnosis_campaign_users_result_idx
  on public.diagnosis_campaign_users (campaign_id, diagnosis_result);

create index if not exists diagnosis_campaign_users_coupon_status_idx
  on public.diagnosis_campaign_users (campaign_id, coupon_send_status, coupon_redeemed_at);

create index if not exists diagnosis_campaign_events_user_time_idx
  on public.diagnosis_campaign_events (campaign_user_id, occurred_at desc);

alter table public.diagnosis_campaign_users enable row level security;
alter table public.diagnosis_campaign_events enable row level security;

create or replace function public.register_diagnosis_campaign_open(
  p_campaign_id text,
  p_line_user_id text,
  p_line_display_name text,
  p_source text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.diagnosis_campaign_users;
  v_was_existing boolean;
begin
  select exists(
    select 1 from public.diagnosis_campaign_users
    where campaign_id = p_campaign_id and line_user_id = p_line_user_id
  ) into v_was_existing;

  insert into public.diagnosis_campaign_users (
    campaign_id, line_user_id, line_display_name, source
  ) values (
    p_campaign_id, p_line_user_id, nullif(p_line_display_name, ''), left(coalesce(p_source, 'line'), 40)
  )
  on conflict (campaign_id, line_user_id) do update set
    line_display_name = coalesce(nullif(excluded.line_display_name, ''), diagnosis_campaign_users.line_display_name),
    source = excluded.source,
    last_opened_at = now(),
    opened_count = diagnosis_campaign_users.opened_count + 1,
    updated_at = now()
  returning * into v_user;

  insert into public.diagnosis_campaign_events (campaign_user_id, event_type, metadata)
  values (
    v_user.id,
    case when v_was_existing then 'duplicate_access' else 'diagnosis_opened' end,
    jsonb_build_object('source', left(coalesce(p_source, 'line'), 40))
  );

  return to_jsonb(v_user) || jsonb_build_object('was_existing', v_was_existing);
end;
$$;

create or replace function public.mark_diagnosis_campaign_started(
  p_campaign_id text,
  p_line_user_id text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.diagnosis_campaign_users;
begin
  update public.diagnosis_campaign_users
  set diagnosis_started_at = coalesce(diagnosis_started_at, now()),
      updated_at = now()
  where campaign_id = p_campaign_id and line_user_id = p_line_user_id
  returning * into v_user;

  if v_user.id is null then raise exception 'campaign_user_not_found'; end if;

  insert into public.diagnosis_campaign_events (campaign_user_id, event_type)
  values (v_user.id, 'diagnosis_started');

  return to_jsonb(v_user);
end;
$$;

create or replace function public.complete_diagnosis_campaign(
  p_campaign_id text,
  p_line_user_id text,
  p_result text,
  p_answers jsonb,
  p_participant_code text,
  p_token text,
  p_pass_type text,
  p_source text,
  p_diagnosed_on date,
  p_event_eligible boolean,
  p_coupon_code text,
  p_coupon_type text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.diagnosis_campaign_users;
begin
  select * into v_user
  from public.diagnosis_campaign_users
  where campaign_id = p_campaign_id and line_user_id = p_line_user_id
  for update;

  if v_user.id is null then raise exception 'campaign_user_not_found'; end if;

  if v_user.diagnosis_completed_at is not null then
    return to_jsonb(v_user) || jsonb_build_object('was_existing', true);
  end if;

  insert into public.diagnosis_participants (
    participant_code, token, diagnosis_result, pass_type, source,
    diagnosed_on, event_eligible, preview_used, updated_at
  ) values (
    p_participant_code, p_token, p_result, nullif(p_pass_type, ''),
    left(coalesce(p_source, 'line'), 40), p_diagnosed_on,
    p_event_eligible, false, now()
  );

  insert into public.participation_events (
    participant_code, event_type, source, metadata
  ) values (
    p_participant_code, 'diagnosis_completed', left(coalesce(p_source, 'line'), 40),
    jsonb_build_object('campaign_id', p_campaign_id, 'answers', p_answers)
  );

  update public.diagnosis_campaign_users
  set diagnosis_started_at = coalesce(diagnosis_started_at, now()),
      diagnosis_completed_at = now(),
      diagnosed_on = p_diagnosed_on,
      diagnosis_result = p_result,
      answers = p_answers,
      participant_code = p_participant_code,
      coupon_code = p_coupon_code,
      coupon_type = p_coupon_type,
      updated_at = now()
  where id = v_user.id
  returning * into v_user;

  insert into public.diagnosis_campaign_events (campaign_user_id, event_type, metadata)
  values (
    v_user.id, 'diagnosis_completed',
    jsonb_build_object('result', p_result, 'participant_code', p_participant_code)
  );

  return to_jsonb(v_user) || jsonb_build_object('was_existing', false);
end;
$$;

create or replace function public.mark_diagnosis_coupon_delivery(
  p_campaign_id text,
  p_line_user_id text,
  p_sent boolean,
  p_error text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.diagnosis_campaign_users;
begin
  update public.diagnosis_campaign_users
  set coupon_send_status = case when p_sent then 'sent' else 'failed' end,
      coupon_sent_at = case when p_sent then coalesce(coupon_sent_at, now()) else coupon_sent_at end,
      coupon_last_error = case when p_sent then null else left(coalesce(p_error, 'unknown'), 500) end,
      updated_at = now()
  where campaign_id = p_campaign_id and line_user_id = p_line_user_id
  returning * into v_user;

  if v_user.id is null then raise exception 'campaign_user_not_found'; end if;

  insert into public.diagnosis_campaign_events (campaign_user_id, event_type, metadata)
  values (
    v_user.id,
    case when p_sent then 'coupon_sent' else 'coupon_send_failed' end,
    case when p_sent then '{}'::jsonb else jsonb_build_object('error', left(coalesce(p_error, 'unknown'), 500)) end
  );

  return to_jsonb(v_user);
end;
$$;

create or replace function public.redeem_diagnosis_coupon(
  p_coupon_code text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.diagnosis_campaign_users;
  v_was_redeemed boolean;
begin
  select * into v_user
  from public.diagnosis_campaign_users
  where coupon_code = upper(trim(p_coupon_code))
  for update;

  if v_user.id is null then raise exception 'coupon_not_found'; end if;
  v_was_redeemed := v_user.coupon_redeemed_at is not null;

  if not v_was_redeemed then
    update public.diagnosis_campaign_users
    set coupon_redeemed_at = now(), updated_at = now()
    where id = v_user.id
    returning * into v_user;
  end if;

  insert into public.diagnosis_campaign_events (campaign_user_id, event_type)
  values (
    v_user.id,
    case when v_was_redeemed then 'coupon_redeem_duplicate' else 'coupon_redeemed' end
  );

  return to_jsonb(v_user) || jsonb_build_object('was_redeemed', v_was_redeemed);
end;
$$;

revoke all on function public.register_diagnosis_campaign_open(text, text, text, text) from public, anon, authenticated;
revoke all on function public.mark_diagnosis_campaign_started(text, text) from public, anon, authenticated;
revoke all on function public.complete_diagnosis_campaign(text, text, text, jsonb, text, text, text, text, date, boolean, text, text) from public, anon, authenticated;
revoke all on function public.mark_diagnosis_coupon_delivery(text, text, boolean, text) from public, anon, authenticated;
revoke all on function public.redeem_diagnosis_coupon(text) from public, anon, authenticated;

grant execute on function public.register_diagnosis_campaign_open(text, text, text, text) to service_role;
grant execute on function public.mark_diagnosis_campaign_started(text, text) to service_role;
grant execute on function public.complete_diagnosis_campaign(text, text, text, jsonb, text, text, text, text, date, boolean, text, text) to service_role;
grant execute on function public.mark_diagnosis_coupon_delivery(text, text, boolean, text) to service_role;
grant execute on function public.redeem_diagnosis_coupon(text) to service_role;

drop view if exists public.sheet_participation_export;
create view public.sheet_participation_export as
select
  p.participant_code,
  p.diagnosed_on,
  p.diagnosis_result,
  p.pass_type,
  p.source,
  p.event_eligible,
  p.preview_used,
  p.artwork_status,
  p.created_at,
  p.updated_at,
  count(e.id) filter (where e.event_type = 'table_qr_opened') as table_qr_count,
  count(e.id) filter (where e.event_type = 'coloring_started') as coloring_start_count,
  count(e.id) filter (where e.event_type = 'artwork_submitted') as artwork_submit_count,
  u.campaign_id,
  u.line_display_name,
  case when u.line_user_id is null then null else '***' || right(u.line_user_id, 6) end as line_user_masked,
  u.answers,
  u.coupon_code,
  u.coupon_type,
  u.coupon_send_status,
  u.coupon_sent_at,
  u.coupon_redeemed_at
from public.diagnosis_participants p
left join public.participation_events e on e.participant_code = p.participant_code
left join public.diagnosis_campaign_users u on u.participant_code = p.participant_code
group by p.id, u.id;

create or replace view public.sheet_diagnosis_funnel_export as
select
  campaign_id,
  line_display_name,
  '***' || right(line_user_id, 6) as line_user_masked,
  source,
  first_opened_at,
  last_opened_at,
  opened_count,
  diagnosis_started_at,
  diagnosis_completed_at,
  diagnosed_on,
  diagnosis_result,
  answers,
  participant_code,
  coupon_code,
  coupon_type,
  coupon_send_status,
  coupon_sent_at,
  coupon_redeemed_at,
  updated_at
from public.diagnosis_campaign_users;

revoke all on public.diagnosis_campaign_users from anon, authenticated;
revoke all on public.diagnosis_campaign_events from anon, authenticated;
revoke all on public.sheet_participation_export from anon, authenticated;
revoke all on public.sheet_diagnosis_funnel_export from anon, authenticated;
